### ISSUE TITLE
Seems unique approval is not working when trying to set to "2"

### ISSUE THREAD

**Issue by richardjimenez52** [taichi/approved-event-action#26]
The following job still passes even though pull request has only one approver on it but setting the input to need 2 approvals. 

```
on: pull_request_review
jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: taichi/approved-event-action@v1.2.1
        id: approved
        with:
          approvals: "2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
