### ISSUE TITLE
Update to marketplace

### ISSUE THREAD

**Issue by janeven** [taichi/approved-event-action#7]
Please create a new release with latest fixes 
and upload to GitHub Marketplace. Great action-plugin btw!

**Comment by MrCaiNinja** [comment]
See comment here: https://github.com/taichi/approved-event-action/pull/6#issuecomment-742079889

The version in marketplace (https://github.com/marketplace/actions/approved-event) is still v1.2.1 with Deprecating set-env and add-path commands, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
The latest in this repo has fixed this with updated @actions/core 1.2.6.

I use this action in my build-workflow and I really want to get rid of the security vulnerability identified by Github.

**Comment by MrCaiNinja** [comment]
Hvilke kommentarer er dette ?

**Comment by richardjimenez52** [comment]
were any of you able to use this action with unique approvers being something other than the default such as 2? This is my action and I have it set to 2 but the action is still passing even though the pull request has only one approver. @MrCaiNinja @janeven @taichi 

```
on: pull_request_review
jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: taichi/approved-event-action@v1.2.1
        id: approved
        with:
          approvals: "2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
